// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://siamvqryqllfgogcqadb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpYW12cXJ5cWxsZmdvZ2NxYWRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3NTAxOTUsImV4cCI6MjA3NzMyNjE5NX0.DYXExkUBiodi-0heYO775Noo-9GUaIj7DydJhaSIYdI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});